### ISSUE TITLE
Querry results disapear when an error occurs in an unrelated cell.

### ISSUE THREAD

**Issue by VanHulleOne** [mgreminger/EngineeringPaper.xyz#159]
When any cell has a syntax error, all previous query results disappear. This is a little annoying when you want to type the result from a previous query into a new cell. I do not fully know how all of the cells interact but I would think an error from a farther down cell could be ignored, at least until the cell currently being edited is exited, by previous cells so their results are still visible. Results from a system cell do remain visible.

**Comment by mgreminger** [comment]
Yes, the intent is to not show results when there is an error in an effort to always have the inputs and results consistent (this is why the solver cells remain unchanged, their results are isolated from the rest of the sheet). Order doesn't matter since a later cell can impact a cell before it. However, you have a good point and I think there is a middle ground. As you suggest, the best approach would be to not delete the results for syntax error until the cell is exited with an error (or after some timeout in the case the user doesn't leave the cell). This gets a little involved since you can have the situation where the user saves the sheet while there is an error in a cell and the results shouldn't be saved in that case. There are probably some other edge cases that need to be considered to make sure that displaying inconsistent results is not possible. I initially took the simplest approach to guarantee consistency, but there is some room for improvement. 

Implementing #160 will a good start to make this a little better.
