### ISSUE TITLE
User selectable default units.

### ISSUE THREAD

**Issue by VanHulleOne** [mgreminger/EngineeringPaper.xyz#164]
Feature/enhancement would be to have user selectable default units. Maybe as global/keyword variables?
`Default_Length = [mm]` or something like that and then any length result that doesn't specifically call out a unit would use that value. I would not expect it to change any other unit for example torque would still come out as N\*m and not N\*mm. For the scale of my work most of the data is in inches or millimeters and having to add the extra four characters (`[mm]` or `[in]`) just to keep my result in the same units as my input data gets old.

The next two ideas are related although I'd aim for the above one first:
1) Detect local cell units, if I type `25[mm] + 75 [mm] =` it would notice than all of my values use the same units and then give me my result in mm. 

2) Allow results in multiple units. `25[mm] + 75[mm] = [mm | in] = 100[mm] | 3.937[in]` I do a lot of work back and forth between English and metric and different people have a better feel for one or the other so I often just present both values. This would save an extra cell just for unit conversion.

In case you couldn't tell I discovered your application this week and think it is pretty great. I am a full time mechanical engineer and was looking for an open source solver that would help me keep track of units and provide easy graphs etc, pretty much everything your work is doing. These "issues" are just to help give you some user feedback. Please keep up the great work!

**Comment by mgreminger** [comment]
Thanks for the feedback and encouragement, much appreciated. I don't notice some of the pain points a new user may notice, so I appreciate the feedback from that prospective.

Yes, I agree that output units should match user units. I actually prefer the approach to keeping track of the units the user is using and mirroring those in the results as apposed to manually specifying the preferred unit. Would need to keep track of units across the entire sheet, since using variables, the user might not specify units in the cell they are querying the result in. This could apply to units on the RHS of a query statement as well, so that a unit would only need to be specified once for compatible units.

Nice idea about allowing querying values with multiple units. It's a little more involved since it involves changing the equation parser, but doable.

I'm working on updating some of the core code from JavaScript to TypeScript (#163) to make some of these changes easier to implement. The current core code is a bit gnarly and hard to update safely because of how it constructs objects on the fly rather than all at once with types.
