### ISSUE TITLE
Comments in Calculations and Multiple Assignments

### ISSUE THREAD

**Issue by JWock82** [mgreminger/EngineeringPaper.xyz#171]
It'd be nice to be able to add comments to the side of a calculation. For example, I'm often using building code prescribed equations and it's nice for the checker to have the code reference right next to the calculation. Putting it in a cell above or below the calculation leaves a lot of white space and needlessly makes the pages longer.

**Comment by mgreminger** [comment]
Nice suggestion, makes sense and shouldn't be too difficult to add. This also gets me thinking about other ways to reduce vertical space. Being able to make multiple assignments in a single math cell would help a lot `x = y = 5 [mm]` for values that are the same and `x = 5 [mm], y = 30[mm]` for the general case. Multiple assignments will take a little longer to implement since it will require a math parser update and I'm currently updating the math parser as part of upgrading the math editor (#167).  Both of these changes combined would help out the vertical space usage quite a bit.

**Comment by JWock82** [comment]
It'd also use half the space if the two lines below could be rendered in one line:
![image](https://user-images.githubusercontent.com/33323539/228693551-5e6532e2-061a-4b03-af6f-684b7721f0c2.png)

**Comment by mgreminger** [comment]
Yes, being able to combine an assignment and a query by putting at equals sign at the end is a good idea as well.

**Comment by JWock82** [comment]
I find seeing the calculated numbers as I go is often helpful in identifying how each parameter weighs into the final solution.

**Comment by JWock82** [comment]
Thanks for this!
